#!/usr/bin/env bash

function gifenc() {
    source "$DOROTHY/sources/bash.bash"

    palette="/tmp/palette.png"
    filters="fps=15"
    #filters="fps=15,scale=320:-1:flags=lanczos"

    ffmpeg -v warning -i "$1" -vf "$filters,palettegen" -y "$palette"
    ffmpeg -v warning -i "$1" -i "$palette" -lavfi "$filters [x]; [x][1:v] paletteuse" -y "$2"
}

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	gifenc "$@"
fi