#!/usr/bin/env bash

function google-chrome-personal() {
    source "$DOROTHY/sources/bash.bash"

    google-chrome --class=Personal "$@"
}

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	google-chrome-personal "$@"
fi