#!/usr/bin/env bash

function slownotify() {
    source "$DOROTHY/sources/bash.bash"

    # Default timeout (in seconds)
    DEFAULT_TIMEOUT=5
    DEFAULT_CANCEL_DELAY=10

    # Parse command line arguments
    timeout=$DEFAULT_TIMEOUT
    cancel_delay=$DEFAULT_CANCEL_DELAY
    custom_message=false

    while getopts "t:c:m:" opt; do
        case "$opt" in
            t) timeout=$OPTARG ;;
            c) cancel_delay=$OPTARG ;;
            m) message=$OPTARG; custom_message=true ;;
            *) echo "Usage: $(basename "$0") [ -t <timeout> ] [ -c <cancel delay> ] [ -m <message> ] <command>" >&2; exit 1 ;;
        esac
    done
    shift $((OPTIND - 1))
    cmd=("$@")

    # Check if any command is specified
    if [[ ${#cmd[@]} -eq 0 ]]; then
    echo "Usage: $(basename "$0") [ -t <timeout> ] [ -c <cancel delay> ] [ -m <message> ] <command>"
    exit 1
    fi

     # Start the command and time its execution
    start_time=$(date +%s)
    set +e
    "${cmd[@]}"

    return_status=$?
    set -e
    end_time=$(date +%s)

    # Calculate the duration using bc for floating point support
    duration=$(echo "$end_time - $start_time" | bc)

    # Check if duration exceeded the timeout using bc
    if [[ $(echo "$duration >= $timeout" | bc) -eq 1 ]]; then

        # Set default message if no custom message is provided
        if [[ "$custom_message" != "true" ]]; then
            message="command finished with status ${return_status} after ${duration}s: ${cmd[*]}"
        fi

        echo "Notifying in ${cancel_delay}s (Ctrl-C to cancel)..."
        sleep "$cancel_delay"

        echo "$message"
        notify "$message"
    fi
 }

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	slownotify "$@"
fi